import test from 'node:test'
import assert from 'node:assert/strict'
import { VoiceCore, aggregateMessage, clampVoiceSentences, estimateSpeechRearmMs, parseVoiceBlocks, ttsEchoSimilarity } from '../src/core.js'
import { normalizeHermesEvent } from '../src/adapters/hermes.js'
import { ownsSession } from '../src/adapters/contract.js'
import { startVoiceSession } from '../src/runtime.js'
class FakeScheduler { constructor() { this.next = 1; this.jobs = new Map() } setTimeout(fn, ms) { const id = this.next++; this.jobs.set(id, { fn, ms }); return id } clearTimeout(id) { this.jobs.delete(id) } runOne() { const [id, job] = this.jobs.entries().next().value ?? []; if (id) { this.jobs.delete(id); job.fn() } } get size() { return this.jobs.size } }
function make(options = {}) { const calls = [], scheduler = new FakeScheduler(), core = new VoiceCore({ ...options, scheduler, onSubmit: x => calls.push(['submit', x]), onSpeak: x => calls.push(['speak', x]), onRecord: (...x) => calls.push(['record', ...x]), onVoice: x => calls.push(['voice', x]), onStatus: x => calls.push(['status', x]) }); return { core, calls, scheduler } }
test('strict blocks, aggregation, five short sentences, unclosed/no-block silence', () => { const five = '하나. 둘. 셋. 넷. 다섯.'; assert.equal(parseVoiceBlocks(`<<<VOICE ${five} VOICE>>>`).text, five); assert.equal(clampVoiceSentences('하나. 둘. 셋. 넷. 다섯. 여섯.'), five); assert.equal(clampVoiceSentences('한 문장입니다.'), '한 문장입니다.'); assert.deepEqual(parseVoiceBlocks('written <<<VOICE one VOICE>>> and <<<VOICE two VOICE>>>').blocks, ['one', 'two']); assert.equal(parseVoiceBlocks('<<<VOICE never').complete, false); assert.equal(aggregateMessage(['<<<VOICE ', 'hello', ' VOICE>>>']), '<<<VOICE hello VOICE>>>'); const { core, calls, scheduler } = make(); core.start('s1'); core.messageStart('s1', { id: 'u' }); core.messageComplete('s1', { id: 'u', text: '<<<VOICE never' }); assert.equal(calls.some(x => x[0] === 'speak'), false); assert.equal(scheduler.size, 1); scheduler.runOne(); core.messageStart('s1', { id: 'n' }); core.messageComplete('s1', { id: 'n', text: 'written only' }); assert.equal(calls.some(x => x[0] === 'speak'), false); assert.equal(scheduler.size, 1) })
test('real RpcEvent normalization and controller ownership survive focus changes', () => { const event = { type: 'voice.transcript', session_id: 's1', payload: { text: '헤이 헤르메스 해줘' } }; const item = normalizeHermesEvent(event); assert.deepEqual(item, { type: event.type, sessionId: 's1', payload: event.payload }); assert.equal(ownsSession(item, 's1'), true); assert.equal(ownsSession(item, 's2'), false); const { core } = make(); core.start('s1'); assert.equal(core.acceptTranscript(item.sessionId, item.payload.text).text, '해줘'); core.voiceStatus('s1', 'idle'); assert.equal(ownsSession(item, 's1'), true) })
test('session switch rejects late events and resets turn identity', () => { const { core, calls } = make(); core.start('s1'); core.messageStart('s1', { id: 'old' }); core.messageDelta('s1', '<<<VOICE 늦은 답 VOICE>>>'); core.start('s2'); assert.equal(core.messageComplete('s1', { id: 'old', text: '<<<VOICE 늦은 답 VOICE>>>' }).ignored, true); assert.equal(calls.some(x => x[0] === 'speak'), false); core.messageStart('s2', { id: 'new' }); core.messageComplete('s2', { id: 'new', text: '<<<VOICE 새 답 VOICE>>>' }); assert.equal(calls.filter(x => x[0] === 'speak').length, 1); assert.equal(core.messageComplete('s2', { id: 'new', text: '<<<VOICE 중복 VOICE>>>' }).spoken, false) })
test('transcript/status payloads, wake alone/command and reactive status callback', () => { const { core, calls, scheduler } = make(); core.start('s1'); const status = normalizeHermesEvent({ type: 'voice.status', session_id: 's1', payload: { state: 'idle' } }); core.voiceStatus(status.sessionId, status.payload.state); assert.equal(core.phase, 'idle'); assert.equal(core.acceptTranscript('s1', '음').accepted, false); assert.equal(core.acceptTranscript('s1', '헤이 헤르메스').armed, true); scheduler.runOne(); assert.equal(core.acceptTranscript('s1', '오늘 일정 알려줘').accepted, true); assert.equal(calls.some(x => x[0] === 'status'), true) })
test('bare wake speaks once, stays interruptible, then rearms once', () => { const { core, calls, scheduler } = make(); core.start('s1'); assert.equal(core.acceptTranscript('s1', '헤이 헤르메스').armed, true); assert.equal(core.phase, 'speaking'); assert.equal(core.afterReply, false); assert.deepEqual(calls.filter(x => x[0] === 'speak'), [['speak', '네, 말씀하세요.']]); assert.equal(calls.filter(x => x[0] === 'record' && x[1] === 'start').length, 1); assert.equal(calls.filter(x => x[0] === 'record' && x[1] === 'stop').length, 1); assert.equal(scheduler.size, 1); core.voiceStatus('s1', 'idle'); assert.equal(core.phase, 'speaking'); scheduler.runOne(); assert.equal(core.phase, 'idle'); assert.equal(core.armed, true); assert.equal(calls.filter(x => x[0] === 'record' && x[1] === 'start').length, 2); assert.equal(scheduler.size, 0) })
test('duplicate wake activation does not duplicate acknowledgement or rearm', () => { const { core, calls, scheduler } = make(); core.start('s1'); core.acceptTranscript('s1', '헤이 헤르메스'); core.wake('s1'); core.wake('s1'); assert.equal(calls.filter(x => x[0] === 'speak').length, 1); assert.equal(scheduler.size, 1); scheduler.runOne(); assert.equal(calls.filter(x => x[0] === 'record' && x[1] === 'start').length, 2); assert.equal(scheduler.size, 0) })
test('wake plus command submits once without acknowledgement', () => { const { core, calls, scheduler } = make(); core.start('s1'); assert.deepEqual(core.acceptTranscript('s1', '헤이 헤르메스 오늘 일정 알려줘'), { accepted: true, text: '오늘 일정 알려줘', interrupted: false }); assert.equal(calls.filter(x => x[0] === 'speak').length, 0); assert.deepEqual(calls.filter(x => x[0] === 'submit'), [['submit', { session_id: 's1', text: '오늘 일정 알려줘' }]]); assert.equal(scheduler.size, 0) })
test('bare wake after reply acknowledges, then accepts the next transcript', () => { const { core, calls, scheduler } = make(); core.start('s1'); core.messageComplete('s1', { id: 'reply', text: '<<<VOICE 답변입니다 VOICE>>>' }); scheduler.runOne(); assert.equal(core.afterReply, true); assert.equal(core.acceptTranscript('s1', '아').reason, 'filler/noise'); assert.equal(core.afterReply, true); assert.equal(core.acceptTranscript('s1', '임의 명령').reason, 'not armed: continue cue or matching choice required'); assert.equal(core.afterReply, true); core.acceptTranscript('s1', '헤이 헤르메스'); assert.equal(core.afterReply, false); assert.equal(calls.filter(x => x[0] === 'speak').length, 2); scheduler.runOne(); assert.equal(core.acceptTranscript('s1', '임의 명령').accepted, true); assert.equal(calls.filter(x => x[0] === 'submit').length, 1); assert.equal(scheduler.size, 0) })
test('meaningful interruption during acknowledgement submits interrupted and cancels rearm', () => { const { core, calls, scheduler } = make(); core.start('s1'); core.acceptTranscript('s1', '헤이 헤르메스'); const result = core.acceptTranscript('s1', '중단해줘'); assert.equal(result.interrupted, true); assert.deepEqual(calls.filter(x => x[0] === 'submit'), [['submit', { session_id: 's1', text: '중단해줘', interrupted: true }]]); assert.equal(core.armed, false); assert.equal(scheduler.size, 0); assert.equal(calls.filter(x => x[0] === 'speak').length, 1) })
test('empty acknowledgement disables wake speech', () => { const { core, calls, scheduler } = make({ wakeAcknowledgement: '' }); core.start('s1'); core.acceptTranscript('s1', '헤이 헤르메스'); assert.equal(calls.filter(x => x[0] === 'speak').length, 0); assert.equal(core.phase, 'listening'); assert.equal(scheduler.size, 1) })
test('proceed and valid/invalid A-B-C gates only after a reply', () => { const { core, scheduler } = make(); core.start('s1'); core.voiceStatus('s1', 'idle'); assert.equal(core.acceptTranscript('s1', '진행해').accepted, true); core.start('s1'); core.messageComplete('s1', { id: 'q', text: '<<<VOICE A 다음 착수, B 나중에. VOICE>>>' }); scheduler.runOne(); assert.equal(core.acceptTranscript('s1', '비').accepted, true); core.start('s1'); core.messageComplete('s1', { id: 'q2', text: '<<<VOICE A 진행, B 중단 VOICE>>>' }); scheduler.runOne(); assert.equal(core.acceptTranscript('s1', '씨').accepted, false); assert.equal(core.acceptTranscript('s1', '진행해').accepted, true) })
test('one bounded rearm and timer cancellation on stop/interruption', () => { const { core, calls, scheduler } = make(); core.start('s1'); core.messageComplete('s1', { id: 'a', text: '<<<VOICE 짧은 답변 VOICE>>>' }); assert.equal(scheduler.size, 1); scheduler.runOne(); assert.equal(calls.filter(x => x[0] === 'record' && x[1] === 'start').length, 2); core.start('s1'); core.messageComplete('s1', { id: 'b', text: '<<<VOICE 긴 답변입니다 VOICE>>>' }); assert.equal(scheduler.size, 1); core.stop(); assert.equal(scheduler.size, 0); core.start('s1'); core.messageComplete('s1', { id: 'c', text: '<<<VOICE 다시 말합니다 VOICE>>>' }); assert.equal(core.acceptTranscript('s1', '새 명령을 실행해').interrupted, true); assert.equal(scheduler.size, 0) })
test('Korean near-echo guard keeps short valid commands', () => { assert.ok(ttsEchoSimilarity('오늘 날씨가 좋습니다', '오늘 날씨가 좋습니') >= 0.86); const { core } = make(); core.start('s1'); core.messageComplete('s1', { id: 'e', text: '<<<VOICE 오늘 날씨가 좋습니다 VOICE>>>' }); core.voiceStatus('s1', 'idle'); assert.equal(core.acceptTranscript('s1', '오늘 날씨가 좋습니').reason, 'tts echo'); core.start('s1'); assert.equal(core.acceptTranscript('s1', 'go').accepted, true) })
test('repeated idle noise re-arms once and empty interruption is ignored', () => { const { core, calls, scheduler } = make(); core.start('s1'); assert.equal(core.reject('filler/noise').accepted, false); assert.equal(scheduler.size, 1); core.reject('filler/noise'); assert.equal(scheduler.size, 1); scheduler.runOne(); assert.equal(calls.filter(x => x[0] === 'record' && x[1] === 'start').length, 2); core.voiceStatus('s1', 'idle'); core.reject('filler/noise'); assert.equal(scheduler.size, 1); core.messageStart('s1', { id: 'i' }); assert.equal(core.acceptTranscript('s1', '').accepted, false); assert.equal(core.lastRejection, 'filler/noise') })
test('generic adapter contract is dependency-free and executable', async () => { const { createExampleAdapter } = await import('../src/adapters/example.js'); const adapter = createExampleAdapter({ getSessionId: () => 'x', toggle: () => {}, record: () => {}, speak: () => {}, submit: () => {}, subscribe: () => () => {} }); assert.equal(adapter.getSessionId(), 'x'); assert.throws(() => createExampleAdapter({}), /required/) })
test('toggle-on resolves before the first record start', async () => { const order = []; const adapter = { toggle: async action => { order.push(`toggle:${action}`); await Promise.resolve(); order.push('toggle:ready') } }; const controller = new VoiceCore({ onRecord: (action) => order.push(`record:${action}`) }); await startVoiceSession(adapter, controller, 's1'); assert.deepEqual(order, ['toggle:on', 'toggle:ready', 'record:start']) })
test('empirical speech estimator is conservative and bounded', () => { const long = estimateSpeechRearmMs('가'.repeat(112)); assert.ok(long >= 16000); assert.ok(long <= 30000); const short = estimateSpeechRearmMs('짧게.'); assert.ok(short >= 500); assert.ok(short < 30000) })
